backend:
  name: github
  repo: kanaabe/brendenclarke

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - { name: slug, label: Slug }
          - { name: title, label: Title }
          - { name: image, label: Image, widget: image }
          - {
              name: mainCopy,
              label: Main Copy,
              widget: markdown,
              required: false,
            }
          - {
              name: subCopy,
              label: Sub Copy,
              widget: markdown,
              required: false,
            }
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: about,
            }
        editor:
          preview: false
  - name: project
    label: Project
    folder: src/pages/project
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: thumbnailImage, label: Thumbnail Image, widget: image }
      - name: mediaList
        label: "Media List"
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: caption, label: Caption, widget: markdown, required: false }
          - { name: media, label: Media, widget: file, required: false }
          - { name: video, label: Video Link, required: false }
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: project,
        }
  - name: settings
    label: Settings
    create: false
    files:
      - name: photographyOrder
        label: Photography Order
        file: src/utils/photographyOrder.md
        fields:
          - { name: title, label: Title }
          - label: Projects List
            name: projects
            widget: list
            fields:
              - label: Project
                name: project
                widget: relation
                collection: project
                searchFields: [title]
                valueField: title
                displayFields: [title]
