backend:
  name: github
  repo: kanaabe/brendenclarke

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: src/pages/index.md
        label: Home
        name: index
        fields:
          - { name: slug, label: Slug }
          - { name: title, label: Title }
          - { name: image, label: Image, widget: image }
          - { name: video, label: Video Link }
          - {
            label: Template Key,
            name: templateKey,
            widget: hidden,
            default: index,
          }
        editor:
          preview: false
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - { name: slug, label: Slug }
          - { name: title, label: Title }
          - { name: image, label: Image, widget: image }
          - { name: mainCopy, label: Main Copy, widget: markdown }
          - { name: subCopy, label: Sub Copy, widget: markdown }
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: about,
            }
        editor:
          preview: false
  - name: project
    label: Project
    folder: src/pages/project
    create: true
    editor:
      preview: false
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - { name: thumbnailImage, label: Thumbnail Image, widget: image }
      - name: category
        widget: select
        label: Category
        options: ["photography", "film"]
      - name: mediaList
        label: "Media List"
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: caption, label: Caption, widget: markdown }
          - { name: media, label: Media, widget: file }
          - { name: video, label: Video Link }
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: project,
        }
