backend:
  name: github
  repo: kanaabe/brendenclarke

media_folder: static/assets
public_folder: assets

collections:
  - name: category
    label: Category
    folder: category
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - name: mediaList
        label: "Media List"
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: caption, label: Caption, widget: markdown }
          - { name: media, label: Media, widget: file }
